language: php
script: "phpunit -c _build/test/phpunit.xml"

# Set php versions
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

# database credentials
mysql:
  database: revo_test
  username: root
  encoding: utf8

before_script:
  - mysql -e 'create database revo_test'
  - sed "s/mysql_string_username']= '';/mysql_string_username']= 'root';/g" _build/test/properties.sample.inc.php | sed "s/config_key'] = 'test';/config_key'] = 'config';/g" > _build/test/properties.inc.php