language: php
script: "phpunit -c ./phpunit.xml"

# Set php versions
php:
  - 5.6

# database credentials
mysql:
  database: revo_test
  username: root
  encoding: utf8

before_script: 'cd _build/test && ./generateConfigs.sh'
