language: php
script: "phpunit -c _build/test/phpunit.xml"

# Set php versions
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

# database credentials
mysql:
  database: revo_test
  username: root
  encoding: utf8

before_script: 'cd _build/test && ./generateConfigs.sh'
